Template translations; better sbrk randomization handling; sincos in plttest.c

diff --git a/gcl/configure.in b/gcl/configure.in
--- a/gcl/configure.in
+++ b/gcl/configure.in
@@ -1064,121 +1064,114 @@ AC_TRY_RUN([#include <unistd.h>
 		AC_MSG_RESULT([no: WARNING you must be able to emulate sbrk: as on mingw or macosx]))
 
 if test "$HAVE_SBRK" = "1" ; then
-	AC_MSG_CHECKING([for randomized sbrk])
-	AC_TRY_RUN([#include <unistd.h>
-		    #include <stdio.h>
-		    int main() {
+
+	AC_CHECK_HEADER(sys/personality.h, true,
+		   AC_MSG_RESULT(sys/personality.h not found))
+
+	AC_MSG_CHECKING([for ADDR_NO_RANDOMIZE constant])
+	AC_TRY_RUN([#include <sys/personality.h>
+         	    #include <stdio.h>
+		    int main(int argc,char *argv[],char *envp[]) {
 			FILE *f;
-			if (!(f=fopen("conftest1","w")))
-				return -1;
-			fprintf(f,"%u",sbrk(0));
+			if (!(f=fopen("conftest1","w"))) return -1;
+			fprintf(f,"%x",ADDR_NO_RANDOMIZE);
 			return 0;
 			}],
-			SBRK=`cat conftest1`,SBRK=0,SBRK=0)
+			ADDR_NO_RANDOMIZE=`cat conftest1`,ADDR_NO_RANDOMIZE=0,ADDR_NO_RANDOMIZE=0)
+	if test "$ADDR_NO_RANDOMIZE" = "0" ; then
+		AC_MSG_RESULT([no, assuming 0x40000])
+		AC_DEFINE_UNQUOTED(ADDR_NO_RANDOMIZE,0x40000)
+	else
+		AC_MSG_RESULT([yes, $ADDR_NO_RANDOMIZE])
+	fi
+
+	AC_MSG_CHECKING([for personality(ADDR_NO_RANDOMIZE) support])
+	AC_TRY_RUN([#include <sys/personality.h>
+                    #include <syscall.h>
+                    #include <unistd.h>
+		    #include <stdio.h>
+		    int main(int argc,char *argv[]) {
+			FILE *f;
+			long oldpers = personality(0xffffffffUL);
+			long retval =  personality(oldpers | ADDR_NO_RANDOMIZE);
+			long newpers = personality(0xffffffffUL);
+			if (!(f=fopen("conftest1","w"))) return -1;
+			fprintf(f,"%d",retval != -1 && newpers & ADDR_NO_RANDOMIZE);
+			return 0;
+			}],
+			CAN_UNRANDOMIZE_SBRK=`cat conftest1`,CAN_UNRANDOMIZE_SBRK=0,CAN_UNRANDOMIZE_SBRK=0)
+
+	if test "$CAN_UNRANDOMIZE_SBRK" != 0 ; then
+		AC_MSG_RESULT(yes)
+		AC_DEFINE(CAN_UNRANDOMIZE_SBRK)
+	else
+		AC_MSG_RESULT(no)
+	fi
+
+	AC_MSG_CHECKING([that sbrk is (now) non-random])
+	AC_TRY_RUN([#include <unistd.h>
+		    #include <stdio.h>
+		    #ifdef CAN_UNRANDOMIZE_SBRK
+		    #include <sys/personality.h>
+                    #include <syscall.h>
+                    #include <unistd.h>
+		    #endif
+		    int main(int argc,char * argv[],char * envp[]) {
+			FILE *f;
+			#ifdef CAN_UNRANDOMIZE_SBRK
+			long pers = personality(0xffffffffUL);
+			if (!(pers & ADDR_NO_RANDOMIZE)) {
+			  long retval=personality(pers | ADDR_NO_RANDOMIZE);
+			  long newpers = personality(0xffffffffUL);
+			  if (retval != -1 && newpers & ADDR_NO_RANDOMIZE)
+			    execve(*argv,argv,envp);    
+			  exit(-1);
+			}
+			#endif
+			if (!(f=fopen("conftest1","w"))) return -1;
+			fprintf(f,"%u",sbrk(0));
+			return 0;
+			}],SBRK=`cat conftest1`,SBRK=0,SBRK=0)
 	if test "$SBRK" = "0" ; then
 		AC_MSG_RESULT(cannot trap sbrk)
 		exit 1
 	fi
 	AC_TRY_RUN([#include <unistd.h>
 		    #include <stdio.h>
-		    int main() {
+		    #ifdef CAN_UNRANDOMIZE_SBRK
+		    #include <sys/personality.h>
+                    #include <syscall.h>
+                    #include <unistd.h>
+		    #endif
+		    int main(int argc,char * argv[],char * envp[]) {
 			FILE *f;
-			if (!(f=fopen("conftest1","w")))
-				return -1;
+			#ifdef CAN_UNRANDOMIZE_SBRK
+			long pers = personality(0xffffffffUL);
+			if (!(pers & ADDR_NO_RANDOMIZE)) {
+			  long retval=personality(pers | ADDR_NO_RANDOMIZE);
+			  long newpers = personality(0xffffffffUL);
+			  if (retval != -1 && newpers & ADDR_NO_RANDOMIZE)
+			    execve(*argv,argv,envp);    
+			  exit(-1);
+			}
+			#endif
+			if (!(f=fopen("conftest1","w"))) return -1;
 			fprintf(f,"%u",sbrk(0));
 			return 0;
-			}],
-			SBRK1=`cat conftest1`,SBRK1=0,SBRK1=0)
+			}],SBRK1=`cat conftest1`,SBRK1=0,SBRK1=0)
 	if test "$SBRK1" = "0" ; then
 		AC_MSG_RESULT(cannot trap sbrk)
 		exit 1
 	fi
-	
-	if test "$SBRK" != "$SBRK1" ; then
+	if test "$SBRK" = "$SBRK1" ; then
 		AC_MSG_RESULT(yes)
-#		AC_CHECK_HEADER(linux/personality.h, true,
-#			   AC_MSG_ERROR(linux/personality.h not found))
-#		AC_TRY_RUN([#include <syscall.h>
-#			    #include <linux/personality.h>
-#	         	    #include <stdio.h>
-#			    #include <unistd.h>
-#			    int main(int argc,char *argv[],char *envp[]) {
-#				FILE *f;
-#				if (!(f=fopen("conftest1","w")))
-#					return -1;
-#				fprintf(f,"%x",ADDR_NO_RANDOMIZE);
-#				return 0;
-#				}],
-#				ADDR_NO_RANDOMIZE=`cat conftest1`,ADDR_NO_RANDOMIZE=0,ADDR_NO_RANDOMIZE=0)
-#		if test "$ADDR_NO_RANDOMIZE" = "0" ; then
-#			AC_MSG_RESULT(cannot get ADDR_NO_RANDOMIZE constant)
-#			exit 1
-#		fi
-#		AC_DEFINE_UNQUOTED(ADDR_NO_RANDOMIZE,$ADDR_NO_RANGOMIZE)
-#
-# Many boxes do not have the definition yet
-#
-		ADDR_NO_RANDOMIZE=0x40000
-		AC_DEFINE_UNQUOTED(ADDR_NO_RANDOMIZE,$ADDR_NO_RANDOMIZE)
-		AC_MSG_CHECKING([for ADDR_NO_RANOMIZE constant])
-		AC_MSG_RESULT($ADDR_NO_RANDOMIZE)
-		AC_CHECK_HEADER(sys/personality.h, true,
-			   AC_MSG_ERROR(sys/personality.h not found))
-		AC_TRY_RUN([#include <syscall.h>
-			    #include <sys/personality.h>
-	         	    #include <stdio.h>
-			    #include <unistd.h>
-			    int main(int argc,char *argv[],char *envp[]) {
-				FILE *f;
-				long pers;
-				pers=personality(-1);
-				if (!(pers & ADDR_NO_RANDOMIZE)) {
-				   personality(pers | ADDR_NO_RANDOMIZE);
-				   execve(*argv,argv,envp);
-                                }
-				if (!(f=fopen("conftest1","w")))
-					return -1;
-				fprintf(f,"%u",sbrk(0));
-				return 0;
-				}],
-				SBRK=`cat conftest1`,SBRK=0,SBRK=0)
-		if test "$SBRK" = "0" ; then
-			AC_MSG_RESULT(cannot trap sbrk)
-			exit 1
-		fi
-		AC_TRY_RUN([#include <syscall.h>
-			    #include <sys/personality.h>
-			    #include <stdio.h>
-			    #include <unistd.h>
-			    int main(int argc,char * argv[],char *envp[]) {
-				FILE *f;
-				long pers;
-				pers=personality(-1);
-				if (!(pers & ADDR_NO_RANDOMIZE)) {
-				   personality(pers | ADDR_NO_RANDOMIZE);
-				   execve(*argv,argv,envp);
-                                }
-				if (!(f=fopen("conftest1","w")))
-					return -1;
-				fprintf(f,"%u",sbrk(0));
-				return 0;
-				}],
-				SBRK1=`cat conftest1`,SBRK1=0,SBRK1=0)
-		if test "$SBRK1" = "0" ; then
-			AC_MSG_RESULT(cannot trap sbrk)
-			exit 1
-		fi
-		AC_MSG_CHECKING([for randomized brk remedy])
-		if test "$SBRK" = "$SBRK1" ; then
-			AC_MSG_RESULT(yes)
-			AC_DEFINE(NEED_NONRANDOM_SBRK)
-		else
-			AC_MSG_RESULT(no)
-			echo "Cannot build with randomized sbrk"
-			exit 1
-		fi 
 	else
 		AC_MSG_RESULT(no)
+		echo "Cannot build with randomized sbrk. Your options:"
+		echo " - upgrade to a kernel/libc that knows about personality(ADDR_NO_RANDOMIZE)"
+		echo " - recompile your kernel with CONFIG_COMPAT_BRK (if it has that option)"
+		echo " - run sysctl kernel.randomize_va_space=0 before using gcl"
+		exit 1
 	fi
 fi
 
@@ -1287,9 +1280,10 @@ AC_MSG_CHECKING(DBEGIN)
 AC_TRY_RUN([#include <stdio.h>
             #include <stdlib.h>
             #include <unistd.h>
-	    #ifdef NEED_NONRANDOM_SBRK
-		   #include <syscall.h>
+	    #ifdef CAN_UNRANDOMIZE_SBRK
 		   #include <sys/personality.h>
+		   #include <syscall.h>
+		   #include <unistd.h>
 	   #endif
 int
 main(int argc,char * argv[])
@@ -1297,11 +1291,14 @@ main(int argc,char * argv[])
   void *b;
   FILE *fp;
 
-#ifdef NEED_NONRANDOM_SBRK
-  pers=personality(-1);
+#ifdef CAN_UNRANDOMIZE_SBRK
+  long pers = personality(0xffffffffUL);
   if (!(pers & ADDR_NO_RANDOMIZE)) {
-   personality(pers | ADDR_NO_RANDOMIZE);
-   execve(*argv,argv,envp);
+    long retval=personality(pers | ADDR_NO_RANDOMIZE);
+    long newpers = personality(0xffffffffUL);
+    if (retval != -1 && newpers & ADDR_NO_RANDOMIZE)
+      execve(*argv,argv,envp);    
+      exit(-1);
   }
 #endif
   fp = fopen("conftest1","w");
