Dynamic libgmp support, overriding with patched functions from local source where necessary

diff --git a/gcl/configure.in b/gcl/configure.in
--- a/gcl/configure.in
+++ b/gcl/configure.in
@@ -239,8 +239,12 @@ AC_ARG_ENABLE(debug,
 	,,enable_debug="no")
 
 AC_ARG_ENABLE(oldgmp,
-	[ --enable-oldgmp will link agains gmp2 instead of gmp3 ]
+	[ --enable-oldgmp will link against gmp2 instead of gmp3 ]
 	,,enable_oldgmp="$def_oldgmp")
+
+AC_ARG_ENABLE(dynsysgmp,
+	[ --enable-dynsysgmp will link against the system libgmp3 overriding certain functions with patched versions from the local source ]
+	,,enable_dynsysgmp="no")
 
 load_opt="0"
 if test "$enable_dlopen" = "yes" ; then
@@ -363,6 +367,7 @@ rm -f makedefsafter
 
 MP_INLCUDE=""
 if test $use_gmp = yes ; then
+
  AC_MSG_CHECKING([use_gmp=yes, doing configure in gmp directory])
  echo
  echo "#"
@@ -391,32 +396,55 @@ if test $use_gmp = yes ; then
  echo "# Subconfigure of GMP done"
  echo "# ------------------------"
  echo "#"
- cp $GMPDIR/gmp.h h/gmp.h
+
+ if test "$enable_dynsysgmp" = "yes" ; then
+	AC_CHECK_HEADER(gmp.h,
+		AC_CHECK_LIB(gmp,__gmpz_init,
+			MPFILES=$GMPDIR/mpn/mul_n.o
+			if test "$use" = "m68k-linux" ; then
+				MPFILES="$MPFILES $GMPDIR/mpn/lshift.o $GOMEDIR/mpn/rshift.o"
+			fi
+			TLIBS="$TLIBS -lgmp"
+			echo "#include \"gmp.h\"" >foo.c
+			echo "int main() {return 0;}" >>foo.c
+			MP_INCLUDE=`cpp foo.c | grep /gmp.h | head -1l | $AWK '{print $3}' | tr -d '"'`
+			rm -f foo.c,
+			echo "Cannot use dynamic gmp lib" ; exit 1,),
+		echo "Cannot use dynamic gmp lib" ; exit 1,)
+
+else			
+
+	cp $GMPDIR/gmp.h h/gmp.h
+	MP_INCLUDE=h/gmp.h
+	MPFILES=$GMPDIR/libgmp.a
+
+fi
+
  AC_MSG_CHECKING("for size of gmp limbs")
  AC_TRY_RUN([#include <stdio.h>
-	#include "h/gmp.h"
+	#include "$MP_INCLUDE"
 	int main() {
 	FILE *fp=fopen("conftest1","w");
 	fprintf(fp,"%u",sizeof(mp_limb_t));
 	fclose(fp);
 	return 0;
-}],mpsize=`cat conftest1`,mpsize=0,mpsize=0)
+	}],mpsize=`cat conftest1`,mpsize=0,mpsize=0)
  if test "$mpsize" = "0" ; then
 	echo "Cannot determine mpsize"
 	exit 1
  fi
  AC_DEFINE_UNQUOTED(MP_LIMB_BYTES,$mpsize)
  AC_MSG_RESULT($mpsize) 
+
  GMP=1
  AC_DEFINE(GMP)
  AC_SUBST(GMP)
  AC_SUBST(GMPDIR)
- MP_INCLUDE=h/gmp.h
+ AC_SUBST(MP_INCLUDE)
  echo > makedefsafter
- echo 'MPFILES=${GMPDIR}/libgmp.a' >> makedefsafter
+ echo "MPFILES=$MPFILES" >> makedefsafter
  echo >> makedefsafter
 fi
-AC_SUBST(MP_INCLUDE)
  
 
 
